name: Release

on:
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-x64
    if: github.repository_owner == 'twilio'
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 20
    strategy:
      matrix:
        node: [22, 24]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Artifactory OIDC Auth
        uses: twilio/sdk-actions/artifactory-oidc@0375437914d535a5fb178bdbfdb5d51bdde2616e

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build

  deploy:
    name: Publish to npm
    needs: [test]
    runs-on: ubuntu-x64
    if: github.repository_owner == 'twilio'
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Artifactory OIDC Auth
        uses: twilio/sdk-actions/artifactory-oidc@0375437914d535a5fb178bdbfdb5d51bdde2616e

      # Node 24+ required for npm OIDC trusted publisher support (npm >= 11.5.1)
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - run: npm ci

      - run: npm run build

      - name: Validate tag + publish to npm
        uses: twilio/sdk-actions/npm-publish@0375437914d535a5fb178bdbfdb5d51bdde2616e
        with:
          registry: 'https://registry.npmjs.org'
          validate-tag: 'true'
          tag-prefix: 'v'
          access: 'public'
          provenance: 'true'
